### ISSUE TITLE
Found 1 certificate(s), expected more

### ISSUE THREAD

**Issue by tkonolige** [meeee/pushproxy#21]
I've been trying to set up push proxy locally. I've set up a certificate chain with a root, intermediate, and leaf certificates. However, psd rejects the connection with the message `Found 1 certificate(s), expected more`. I am also getting `Root certificate is not explicitly trusted` even though it is marked as trusted in the keychain.

**Comment by meeee** [comment]
No response for a while, please reopen if you still need help.
