### ISSUE TITLE
Can this be used to solve the revoked enterprise certificate problem ?

### ISSUE THREAD

**Issue by guowseu** [meeee/pushproxy#23]
Dear,

When open app on iPhone, apple will check the certificate validation for app. As I know, the following checking will be made by apple.

Certificate validation 
The first time a user opens an app, the distribution certificate is validated by contacting Apple’s OCSP server. Unless the certificate has been revoked, the app is allowed to run. Inability to contact or get a response from the OCSP server isn’t interpreted as a revocation. To verify the status, the device must be able to reach ocsp.apple.com. See “Network Configuration Requirements,” earlier in this appendix. 

The OCSP response is cached on the device for the period of time specified by the OCSP server—currently, between three and seven days. The validity of the certificate isn’t checked again until the device has restarted and the cached response has expired. 

If a revocation is received at that time, the app is prevented from running. 

Revoking a distribution certificate invalidates all of the apps you’ve signed with it. You should revoke a certificate only as a last resort— if you’re sure the private key is lost or the certificate is believed to be compromised.

Can we use this to prevent connecting Apple’s OCSP server ? 
Thanks a lot.

**Comment by mfrister** [comment]
Why do you think the OCSP check has anything to do with the push service?

I'm pretty sure the OCSP revocation check works [via HTTP](https://tools.ietf.org/html/rfc6960#appendix-A). I guess an HTTP man-in-the-middle proxy like [mitmproxy](http://mitmproxy.org/) would help you with this.

**Comment by mfrister** [comment]
No response, closing. Please reopen if you still think this is relevant to pushproxy.
