### ISSUE TITLE
[debug-cert-verification-dtrace.md] Probe doesn't exist on 10.12

### ISSUE THREAD

**Issue by maratsarbasov** [meeee/pushproxy#30]
Hi. I'm trying to debug certificate verification on macOS 10.12.4. 
SIP is disabled. Error when executing dtrace script:
`dtrace: invalid probe specifier security_debug*:Security:secdebug_internal:log /copyinstr(arg0) != "cmutex"/ { printf("%s %s %s", execname, copyinstr(arg0), copyinstr(arg1)) }: probe description security_debug*:Security:secdebug_internal:log does not match any probes`

**Comment by mfrister** [comment]
I don't see how this is related to PushProxy. This is not a generic support forum, closing.
