### ISSUE TITLE
get iPhone's private key

### ISSUE THREAD

**Issue by Rico358097990** [meeee/pushproxy#33]
Is there any other way to get the iPhone's private key？（iPhone is no jailbreak）

**Comment by mfrister** [comment]
Unfortunately, for iOS, you'll need a jailbroken device - the key is device-specific and not backed up (as far as I remember and I can't see a reason it would be).

**Comment by Rico358097990** [comment]
Do you know MDM? maybe it can extract the private Key without jailbreak(I'm not sure)

**Comment by mfrister** [comment]
@Rico358097990 It can't - Apple has no interest in enterprises being able to intercept push notifications. I'm quite sure they have strict certificate pinning by now.

**Comment by Rico358097990** [comment]
hi @mfrister 
What parameters should I pass to /setup/ios/patch-apsd.sh, I don't konw IOS_HOST&PUSH_HOST mean,
IOS_HOST="$1"
PUSH_HOST="$2"

**Comment by Rico358097990** [comment]
I have run the shell，I already knew “IOS_HOST”，and “ PUSH_HOST” I pass 14 random char ，this shell run successfully , next then  "chmod +x apsd & kill apsd" ,but apsd didn't request a new push certificate

**Comment by Rico358097990** [comment]
can you tell me how apple create the cert's common name @mfrister
